const {STRING} = require('sequelize');
module.exports = {
	name: 'REQUESTS_CATEGORIES',
	define: {
		ID_CAT: STRING,
		ID_SCAT: STRING,
		CATEGORIE: STRING,
		CATEGORIE_EN: STRING,
		S_CATEGORIE: STRING,
		S_CATEGORIE_EN: STRING,
		CAT_DESCRIPTION_EN: STRING,
		CAT_DESCRIPTION: STRING,
		SCAT_DESCRIPTION: STRING,
		SCAT_DESCRIPTION_EN: STRING,
	}
}
