const {STRING, REAL, INTEGER, BOOLEAN, TINYINT, TIME, DATE} = require('sequelize');

module.exports = {
  name: 'REQUESTS',
  define: {
    REQUEST_ID: STRING,
    REQUEST_CATEGORY_ID: {
      type: STRING,
      ref: 'REQUESTS_CATEGORIES',
      key: 'ID_SCAT',
    },
    CLASS_ID: STRING,
    SUBJECT_ID: STRING,
    REQUEST_AUTHOR: {
      type: STRING,
      ref: 'EMPLOYEES',
      key: 'MATRICULE',
    },
    CONTRACT_NUMBER: STRING,
    YEAR_ID: STRING,
    TH_DISPLAYED: REAL,
    TH_EXPECTED: REAL,
    VH_DISPLAYED: INTEGER,
    VH_EXPECTED: INTEGER,
    TI_DISPLAYED: REAL,
    TI_EXPECTED: REAL,
    AMOUNT_RECEIVED: REAL,
    REQUEST_PBLM_DATE: DATE,
    REQUEST_PBLM_WEEK: STRING,
    REQUEST_STATUS: STRING,
    REQUEST_FILE: STRING,
    REQUEST_ESCALADE: TINYINT,
    REQUEST_OBJECT: STRING,
    AMOUNT_EXPECTED: REAL,
    DESCRIPTION: STRING,
    REQUEST_UNITY_ID: INTEGER,
    REPRO_STUDENT_COUNT: INTEGER,
    REPRO_COPY_NUMBER: INTEGER,
    REQUEST_UNITY_TRANSMISSIBLE: BOOLEAN,
    PRINTED: BOOLEAN,
    REQUEST_PBLM_HOUR_START: TIME,
    REQUEST_PBLM_HOUR_END: TIME,
  }
}
