const {STRING, REAL} = require('sequelize');
module.exports = {
	name: 'REQUEST_STEP_CONFIGS',
	define: {
		RSTEP_ID: STRING,
		RSTEP_CAT_ID: STRING,
		RSTEP_UNITY_ID: STRING,
		RSTEP_DEST_ID: STRING,
		RSTEP_DELAY_O: REAL,
		RSTEP_STATUS_O: STRING,
		RSTEP_DELAY_W: REAL,
		RSTEP_STATUS_W: STRING,
		RSTEP_DELAY_L: REAL,
		RSTEP_STATUS_L: STRING,
	}
}
