const {INTEGER, STRING} = require("sequelize");
module.exports = {
  name: 'REQUEST_DISPLAY_CONFIGS',
  define: {
    REQUEST_CATEGORY_ID: STRING,
    CLASS_ID: INTEGER,
    SUBJECT_ID: INTEGER,
    CONTRACT_NUMBER: INTEGER,
    REQUEST_PBLM_WEEK: INTEGER,
    REQUEST_PBLM_DATE: INTEGER,
    TH_DISPLAYED: INTEGER,
    TH_EXPECTED: INTEGER,
    VH_DISPLAYED: INTEGER,
    VH_EXPECTED: INTEGER,
    TI_DISPLAYED: INTEGER,
    TI_EXPECTED: INTEGER,
    AMOUNT_RECEIVED: INTEGER,
    REPRO_COPY_NUMBER: INTEGER,
    REPRO_STUDENT_COUNT: INTEGER,
    AMOUNT_EXPECTED: INTEGER,
    DESCRIPTION: INTEGER,
    TIME_TABLE: INTEGER,
    EVENT_DAY: INTEGER,
    EVENT_HOUR: INTEGER,
    FILE: INTEGER,
  }
}
