const {STRING, INTEGER, BOOLEAN, DATE, Sequelize, DATEONLY} = require('sequelize')

module.exports = {
	name: "CANDIDATES",
	freezeTableName: true,
	define: {
		EMAIL: STRING,
		PHONE_NUMBER: STRING,
		LASTNAME: STRING,
		FIRSTNAME: STRING,
		COUNTRY: STRING,
		BIRTHDATE: DATEONLY,
		BIRTHPLACE: STRING,
		GENDER: STRING,
		DEPARTMENT: STRING,
		CIVIL_STATUS: STRING,
		FORMATION_TYPE: STRING,
		ADMISSION_DIPLOMA: STRING,
		LAST_YEAR_RANK: STRING,
		SCHOOL_OBTENTION: STRING,
		FIRST_YEAR_UNIVERSITY: STRING,
		EMERGENCY_CONTACT: STRING,
		FATHER_CONTACT: STRING,
		MOTHER_CONTACT: STRING,
		FORMATION_FIRST_CHOICE: STRING,
		FORMATION_SECOND_CHOICE: STRING,
		CYCLE: STRING,
		MENTION_OBTAINED: STRING,
		IS_PROFESSIONAL: STRING,
		CODE: STRING,
		LAST_YEAR_SITUATION: STRING,
		INTERTAINMENT: STRING,
		IS_HANDICAPED: STRING,
		FIRST_SPORT: STRING,
		EMERGENCY_NAME: STRING,
		FATHER_NAME: STRING,
		FATHER_JOB: STRING,
		MOTHER_NAME: STRING,
		MOTHER_JOB: STRING,
		FIRST_YEAR_UNIVERSITY_TYPE: STRING,
		SECOND_LANGUAGE: STRING,
		FIRST_LANGUAGE: STRING,
		REGION_ORIGIN: STRING,
		LIVING_TOWN: STRING,
		MATRICULE: STRING,
		STAB: STRING,
		ACTIVATED: {
			type: BOOLEAN, defaultValue: false
		},
		HAS_EMAIL_VERIFIED: {
			type: BOOLEAN, defaultValue: false
		},
	}
}
