const {STRING, INTEGER, DATEONLY} = require("sequelize");
module.exports = {
	name: 'DOCUMENTS',
	define: {
		PIECE_TYPE: STRING,
		EMPLOYEE: STRING,
		DESIGNATION: STRING,
		SPECIALITY: STRING,
		LEVEL: INTEGER,
		LANGUAGE: STRING,
		OBTENEDDATE: DATEONLY,
		OBTENEDSTAB: STRING,
		FILE: STRING,
	}
}
