const {STRING, INTEGER} = require('sequelize');

module.exports = {
  name: 'SUBJECTS',
  define: {
    CLASS_ID: STRING,
    LEVEL_ID: STRING,
    SUBJECT_ID: STRING,
    SUBJECT_NAME: STRING,
    SUBJECT_SHORTNAME: STRING,
    SUBJECT_STATUS: STRING,
    SUBJECT_ABREVIATION: STRING,
    SUBJECT_VH_AB_INITIAL: INTEGER,
    SUBJECT_VH_CM_INITIAL: INTEGER,
    SUBJECT_VH_EX_INITIAL: INTEGER,
    SUBJECT_VH_TD_INITIAL: INTEGER,
    SUBJECT_VH_MT_INITIAL: INTEGER,
    SUBJECT_VH_TP_INITIAL: INTEGER,
    RECURENCE: INTEGER,
  }
}
